/* tslint:disable */
/* eslint-disable */
/**
 * Parking space sharing
 * Project created by trainees ofBakcyl Programowania in 2022/2023.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

